
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '`RFo%u.\x08hk\xff\xa8\x98.\xb52'
    
_lr_action_items = {'RPAREN':([1,3,6,7,12,13,14,15,16,17,],[-7,-8,-9,13,-5,-6,-1,-4,-2,-3,]),'ATTR':([0,2,5,8,9,10,11,],[6,6,6,6,6,6,6,]),'NUMBER':([0,2,5,8,9,10,11,],[1,1,1,1,1,1,1,]),'TIMES':([1,3,4,6,7,12,13,14,15,16,17,],[-7,-8,11,-9,11,-5,-6,11,-4,11,-3,]),'PLUS':([1,3,4,6,7,12,13,14,15,16,17,],[-7,-8,8,-9,8,-5,-6,-1,-4,-2,-3,]),'LPAREN':([0,2,5,8,9,10,11,],[2,2,2,2,2,2,2,]),'VARIABLE':([0,2,5,8,9,10,11,],[3,3,3,3,3,3,3,]),'$end':([1,3,4,6,12,13,14,15,16,17,],[-7,-8,0,-9,-5,-6,-1,-4,-2,-3,]),'MINUS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[5,-7,5,-8,10,5,-9,10,5,5,5,5,-5,-6,-1,-4,-2,-3,]),'DIVIDE':([1,3,4,6,7,12,13,14,15,16,17,],[-7,-8,9,-9,9,-5,-6,9,-4,9,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,5,8,9,10,11,],[4,7,12,14,15,16,17,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression_plus','/home/chenwei/trunk/tools/gen_code_tools/mulacula/grammar.py',50),
  ('expression -> expression MINUS expression','expression',3,'p_expression_minus','/home/chenwei/trunk/tools/gen_code_tools/mulacula/grammar.py',54),
  ('expression -> expression TIMES expression','expression',3,'p_expression_times','/home/chenwei/trunk/tools/gen_code_tools/mulacula/grammar.py',58),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_divide','/home/chenwei/trunk/tools/gen_code_tools/mulacula/grammar.py',62),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','/home/chenwei/trunk/tools/gen_code_tools/mulacula/grammar.py',66),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','/home/chenwei/trunk/tools/gen_code_tools/mulacula/grammar.py',73),
  ('expression -> NUMBER','expression',1,'p_expression_number','/home/chenwei/trunk/tools/gen_code_tools/mulacula/grammar.py',77),
  ('expression -> VARIABLE','expression',1,'p_expression_variable','/home/chenwei/trunk/tools/gen_code_tools/mulacula/grammar.py',81),
  ('expression -> ATTR','expression',1,'p_expression_attr','/home/chenwei/trunk/tools/gen_code_tools/mulacula/grammar.py',91),
]
